# Machine Learning Model (Decision Tree Regressor)

In [1]:
import os

In [2]:
os.getcwd()

'C:\\Users\\Dell\\Machine Learning Model'

In [3]:
os.chdir('C:\\Users\\Dell')

In [4]:
os.getcwd()

'C:\\Users\\Dell'

# Example 1

In [12]:
import numpy as np
import pandas as pd

In [17]:
odi=pd.read_csv("ODI.csv")
odi.head()

mid       date                                 venue bat_team bowl_team  \
0    1  6/13/2006  Civil Service Cricket Club, Stormont  England   Ireland   
1    1  6/13/2006  Civil Service Cricket Club, Stormont  England   Ireland   
2    1  6/13/2006  Civil Service Cricket Club, Stormont  England   Ireland   
3    1  6/13/2006  Civil Service Cricket Club, Stormont  England   Ireland   
4    1  6/13/2006  Civil Service Cricket Club, Stormont  England   Ireland   

          batsman       bowler  runs  wickets  overs  runs_last_5  \
0  ME Trescothick  DT Johnston     0        0    0.1            0   
1  ME Trescothick  DT Johnston     0        0    0.2            0   
2  ME Trescothick  DT Johnston     4        0    0.3            4   
3  ME Trescothick  DT Johnston     6        0    0.4            6   
4  ME Trescothick  DT Johnston     6        0    0.5            6   

   wickets_last_5  striker  non-striker  total  
0               0        0            0    301  
1               0        0            0    301  
2               0        0            0    301  
3               0        0            0    301  
4               0        0            0    301

In [18]:
odi=odi.drop(columns=["mid","date","venue","bat_team","bowl_team","batsman","bowler"])       #Remove Unwanted Columns
odi.head()

runs  wickets  overs  runs_last_5  wickets_last_5  striker  non-striker  \
0     0        0    0.1            0               0        0            0   
1     0        0    0.2            0               0        0            0   
2     4        0    0.3            4               0        0            0   
3     6        0    0.4            6               0        0            0   
4     6        0    0.5            6               0        0            0   

   total  
0    301  
1    301  
2    301  
3    301  
4    301

# Step 1

In [19]:
X=odi.drop(columns=["total"])                                                 #Feature variables

In [20]:
X.head()

runs  wickets  overs  runs_last_5  wickets_last_5  striker  non-striker
0     0        0    0.1            0               0        0            0
1     0        0    0.2            0               0        0            0
2     4        0    0.3            4               0        0            0
3     6        0    0.4            6               0        0            0
4     6        0    0.5            6               0        0            0

In [21]:
y=odi["total"]                                                                #Target Variable

In [22]:
y.head()

0    301
1    301
2    301
3    301
4    301
Name: total, dtype: int64

# Rules

In [23]:
X.dtypes

runs                int64
wickets             int64
overs             float64
runs_last_5         int64
wickets_last_5      int64
striker             int64
non-striker         int64
dtype: object

In [24]:
type(X)

pandas.core.frame.DataFrame

In [25]:
X.shape

(350899, 7)

In [26]:
odi.isna().sum()

runs              0
wickets           0
overs             0
runs_last_5       0
wickets_last_5    0
striker           0
non-striker       0
total             0
dtype: int64

In [27]:
#We dont need to use Scaling Methods/Feature Scaling for DecisionTreeClassifier and DecisionTreeRegressor

# Step 2

In [30]:
from sklearn.model_selection import train_test_split

In [38]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [39]:
# We dont need to use stratify=y for Regression Model.

# Step 3

In [40]:
from sklearn.tree import DecisionTreeRegressor

In [41]:
tree=DecisionTreeRegressor()

In [42]:
tree.fit(X_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

# Step 4

# Evaluate

In [43]:
tree.score(X_test,y_test)

0.6676189205895536

# Predict

In [45]:
tree.predict(X_test)

array([220., 220., 256., ..., 228., 139., 292.])

# Predicting on New Observations

In [46]:
data=pd.DataFrame([{"runs":60,"wickets":1,"overs":10.0,"runs_last_5":10,"wickets_last_5":0,"striker":40,"non-striker":3}])

In [47]:
data

runs  wickets  overs  runs_last_5  wickets_last_5  striker  non-striker
0    60        1   10.0           10               0       40            3

In [48]:
tree.predict(data)

array([268.])

# Predicting on New Observations

In [53]:
# For the DataFrame, the Column Name Doesn't Matter.

In [55]:
data1=pd.DataFrame([{0:60,1:1,2:10.0,3:10,4:0,5:40,6:3}])

In [56]:
data1                                            

0  1     2   3  4   5  6
0  60  1  10.0  10  0  40  3

In [57]:
tree.predict(data1)

array([268.])